### ISSUE TITLE
Matt 5:5  "gentle"

### ISSUE THREAD

**Issue by Tchambrers** [openenglishbible/Open-English-Bible#126]
In Matt 5:5 it translates the greek word "praus" as "gentle"  This seems perhaps an old fashioned use of the word. 

Other translations chose the word "meek" or "humble."  I've seen some commentaries that claim that Praus means somethink akin to "power under control" which is hard to translate into any single modern english word.  Almost "self-restrained" would fit that if these commentaries are accurate. 

I have NO set answer here, but wanted to raise the question... and note that the term "praus" as needing good thought beyond it's current translation as "gentle."

**Comment by openenglishbible** [comment]
Gentle is used in REB, HSCB (though not CSB), GWord. This may not be perfect but meets our criteria at the moment, so I'm closing. Potentially we can come back to this later.
