### ISSUE TITLE
Matthew 5:5 "land"

### ISSUE THREAD

**Issue by Tchambrers** [openenglishbible/Open-English-Bible#127]
In Matt 5:5 it translates the greek word gé as "earth."  But the word seems that it can mean "earth" or "land."  http://strongsnumbers.com/greek/1093.htm

My thinking: Whereas "land" could be regional but also could be a global term the word "earth" implies strongly the entire global planet. Since to my amateur eyes, the orginal greek "Ge" is not clear if it is referring to just regional land or the entire earth, then we should choose English words that are equally imprecise.  Thus "land" seems like a better translation.

**Comment by openenglishbible** [comment]
It's an interesting thought, but the use of 'earth' here is pretty much universal in English translations so closing in accordance with our Translation Guidelines.
