### ISSUE TITLE
Mark 1:28 - Better-Wording "Neighborhood"

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#137]
The OEB currently reads,

"And the fame of Jesus spread at once in all directions, through the whole neighborhood of Galilee."

While strictly speaking correct I believe neighborhood conveys a more residential or urban sense than something like region (NRSV, NIV, NET) or vicinity (HSBC). I would recommend region,

"And the fame of Jesus spread at once in all directions, through the whole <b>region</b> of Galilee."

**Comment by openenglishbible** [comment]
Fixed - now uses 'region'
