### ISSUE TITLE
Mark 2:3 - Accuracy/Better Wording

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#147]
The OEB currently reads:

"Some people came bringing to him a paralyzed man, who was being carried by four bearers."

The word 'people' is merely implied by the underlying Greek and might read better as,

"Some came bringing to him a paralyzed man, who was being carried by four bearers."

**Comment by openenglishbible** [comment]
I'm not worried - there is no question that the beings bringing the man were people (!), and the wording is better in English.
