### ISSUE TITLE
Mark 3:21 - Old-Fashioned 'relations'

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#182]
The OEB currently reads,

"When his relations heard of it, they went to take charge of him, for they said that he was out of his mind."

'relations' here is Old-Fashioned. Perhaps 'relatives' or 'family'?

"When his <b>family</b> heard of it, they went to take charge of him, for they said that he was out of his mind."

**Comment by openenglishbible** [comment]
Fixed
