### ISSUE TITLE
Mark 4:1 - "Sea" - Capitalization

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#241]
The OEB currently reads, "Jesus again began to teach by the Sea; and, as an immense crowd was gathering around him, he got into a boat, and sat in it on the Sea, while all the people were on the shore at the water’s edge."

Not sure why "Sea" is capitalized here. Recommend:

"Jesus again began to teach by the sea; and, as an immense crowd was gathering around him, he got into a boat, and sat in it on the sea, while all the people were on the shore at the water’s edge. "

**Comment by openenglishbible** [comment]
Fixed
