### ISSUE TITLE
Mark 1:26 - "fit" Old-Fashioned/Better Wording"

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#283]
The OEB currently reads,

"The foul spirit threw the man into a fit, and with a loud cry came out from him."

"Fit" in the sense of spasm, seizure, or convulsions seems both old fashioned and potentially ambiguous. I recommend replacing it with seizure:

"The foul spirit threw the man into a seizure, and with a loud cry came out from him."

**Comment by openenglishbible** [comment]
Leaving this as 'fit' at this stage.
