### ISSUE TITLE
Mark 1:38 - Accuracy "country towns nearby"

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#296]
The OEB currently reads:

"But Jesus said to them: “Let us go somewhere else, into the country towns nearby so that I can make my proclamation in them also; for that was why I came.”"

"country" appears to be a translators gloss recommend omitting and altering to a more natural word order of "nearby towns":

"But Jesus said to them: “Let us go somewhere else, into the nearby towns so that I can make my proclamation in them also; for that was why I came.”"

**Comment by openenglishbible** [comment]
I'm not sure it is a gloss so much as communicating the idea that we're not talking about the urban conglomerations we might thing of as 'towns' but something smaller - cf NJB 'country towns' NET 'villages' (also HCSB, CEB, NIV), GWORD 'small towns'

Will leave for moment.
