### ISSUE TITLE
Mark 1:43-44 Incorrect Verse Break

### ISSUE THREAD

**Issue by DJHugger** [openenglishbible/Open-English-Bible#297]
The OEB currently reads,

"43  and then Jesus, after sternly warning him, immediately sent him away, and said to him: 44  “Be careful not to say anything to anyone; but go and show yourself to the priest, and make the offerings for your cleansing directed by Moses, as evidence of your cure.”"

Verse 44 should begin earlier before "and said to him". Recommend changing:

""43  and then Jesus, after sternly warning him, immediately sent him away, 44 and said to him:  “Be careful not to say anything to anyone; but go and show yourself to the priest, and make the offerings for your cleansing directed by Moses, as evidence of your cure.”"

**Comment by openenglishbible** [comment]
Fixed with commit https://github.com/openenglishbible/Open-English-Bible/commit/e0b2507306a909ef402eb2ec507794b520d66ccd
