### ISSUE TITLE
"name of Jesus" - Accuracy

### ISSUE THREAD

**Issue by vargose** [openenglishbible/Open-English-Bible#318]
"Faith of" should be changed to "name of" in Matthew 28:19, Acts 2:38, 8:16, 10:48, 19:5, 1 Corinthians 1:13, 1:15 consistent with the same Greek word, onoma, in Acts 3:6, 4:10, 4:18, 4:30, 5:40, 8:12, 9:27, 15:26, 16:18, 19:13, 19:17, 21:13, 22:16, 26:9, 1 Corinthians 1:2, 1:10, 5:4, 6:11, Ephesians 5:20, Philippians 2:10, Colossians 3:17, 2 Thessalonians 1:12, 3:6.

**Comment by openenglishbible** [comment]
Thanks, fixed in https://github.com/openenglishbible/Open-English-Bible/commit/ab9912fa0efcb7123002debbd56cfe6b8f480283
