### ISSUE TITLE
As seen in your file updated last in the website - Pls clarify -  Hebrews 10:37 - ere

### ISSUE THREAD

**Issue by AlleluiaPrints** [openenglishbible/Open-English-Bible#338]
For there is indeed but a very little while 
ere (should it be 'and' or any other alternate word you propose)

**Comment by countingpine** [comment]
Looks like there are few instances of "ere": https://github.com/openenglishbible/Open-English-Bible/search?q=ere

They could probably all be updated to "before".

https://www.merriam-webster.com/dictionary/ere

**Comment by openenglishbible** [comment]
I've changed to 'before' and flagged 'ere' in the checker so that it is removed from other unpublished books before publication.
