### ISSUE TITLE
Link to text version broken

### ISSUE THREAD

**Issue by iamabsmith** [openenglishbible/Open-English-Bible#339]
Steps to reproduce:
1. go to https://openenglishbible.org/
2. click the US spelling download link for "Text". > https://openenglishbible.org/oeb/2020.2/OEB-2020.2-US.txt

Actual result: 404 page not found
Expected result: access to the most recent text version of the Open English Bible (2002.2)

Note: The same happens for the UK spelling Text link as well.  > https://openenglishbible.org/oeb/2020.2/OEB-2020.2-Cth.txt

**Comment by openenglishbible** [comment]
The files were there, but sadly misnamed.
Fixed now.
