### ISSUE TITLE
[Esther 2:6] Typo for Nebuchadnezzar

### ISSUE THREAD

**Issue by omarandlorraine** [openenglishbible/Open-English-Bible#345]
In Esther 2, there is a typo.

It says "whom Nebuchadrezzar the king of Babylon took captive"

The name is Nebuchadnezzar; note the spelling "dn" instead of "dr".

**Comment by countingpine** [comment]
Interestingly, Nebuchadrezzar is a variant of Nebuchadnezzar (https://www.tyndale.com/sites/tyndalebibles/nebuchadnezzar-or-nebuchadrezzar-king-of-babylon/), but the 'r' spelling - based on the KJV translation - is only used in Ezekiel and parts of Jeremiah.

I don't know whether unifying his name in general would be in line with the translation principles of the OEB, but this instance is probably worth changing to bring in line with most/all other translations.

**Comment by openenglishbible** [comment]
Fixed
